version: '3.5'

x-rack: &rack
  command: bash -c "bundle exec rake prod_up && bundle exec unicorn -c config/unicorn.rb"
  image: 18xx_rack:prod
  environment:
    RACK_ENV: production
    DATABASE_URL: $DATABASE_URL
    ELASTIC_KEY: $ELASTIC_KEY
    NEW_RELIC_LICENSE_KEY: $NEW_RELIC_LICENSE_KEY
    RUBYOPTS: --jit
    PORT: 9292
  build:
    args:
      RACK_ENV: production
    context: .
  volumes:
    - ./public:/18xx/public
  depends_on:
    - db
    - redis
  ports:
    - 9292:9292
  logging:
    options:
      max-size: "50m"

services:
  rack:
    <<: *rack

  # rack_backup:
  #  <<: *rack
  #  build:
  #    context: .
  #  ports:
  #    - 9292:9292
  
  queue:
    <<: *rack
    command: bundle exec ruby queue.rb

  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  nginx:
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - ./public:/public
      - /etc/18xxgames/ssl:/etc/18xxgames/ssl
    depends_on:
      - rack
      - rack_backup
    logging:
      options:
        max-size: "300m"
